### ISSUE TITLE
Wrong colors on SG-1000 game

### ISSUE THREAD

**Issue by litaniast** [drhelius/Gearsystem#29]
I used libretro, but when I tried SG-1000 games in GearSystem core, color is wrong.
![Bomb Jack-200524-162430](https://user-images.githubusercontent.com/4857928/82748232-53f22c00-9ddb-11ea-99a4-cc068727c250.png)

correct color in Genesis Plus GX core:
![Bomb Jack-200524-162545](https://user-images.githubusercontent.com/4857928/82748237-5b193a00-9ddb-11ea-951a-fbd165b7b76b.png)

**Comment by drhelius** [comment]
Thanks for reporting.
In which platform are you testing it?

**Comment by litaniast** [comment]
Runs on libretro, Windows 10 x64 version and RockPro64(linux ARM device). Both have that colors.

**Comment by drhelius** [comment]
I'll have a look thanks

**Comment by drhelius** [comment]
It should be fixed.
Could you verify?

**Comment by litaniast** [comment]
![Bomb Jack-200525-205700](https://user-images.githubusercontent.com/4857928/82810825-5bdcc980-9eca-11ea-983e-25f314718f88.png)
not fixed yet

**Comment by drhelius** [comment]
Are you sure you are using the latest version?
It should be Gearsystem 3.1.1.
Are you building it yourself?

**Comment by litaniast** [comment]
> Are you sure you are using the latest version?
> It should be Gearsystem 3.1.1.
> Are you building it yourself?

I used the latest version in buildbot, but it's 3.10. I used the version after the ticket closed.

**Comment by drhelius** [comment]
I just downloaded the "latest" vesion from buildbot and it is 3.1.1 now, with fixed colors.
Maybe you got an older version?
https://buildbot.libretro.com/nightly/linux/x86_64/latest/

**Comment by litaniast** [comment]
I checked linux armv7-neon-hf, it confirmed to fixed and version 3.1.1.
But, in Windows x64, it still 3.1.0 and not fixed. I think buildbot for Windows has problem.
http://buildbot.libretro.com/nightly/windows/x86_64/latest/

**Comment by drhelius** [comment]
I'm afraid I can't help with buildbot as the only thing I can do is pushing new versions so they can be built, as I did.

**Comment by litaniast** [comment]
I'll check the next buildbot update. If it still doesn't update, I'll ask the libretro maintainers.

**Comment by drhelius** [comment]
Thanks, and thanks for reporting as this bug went unnoticed.

**Comment by litaniast** [comment]
Buildbot is updated, but it still says 3.1.0 on Windows x64 core.

**Comment by litaniast** [comment]
Finally, buildbot update confirmed in Windows x64 version of libretro. Thanks for fix.
![Bomb Jack-200527-075357](https://user-images.githubusercontent.com/4857928/82958018-5c22b500-9fef-11ea-8372-de989b54929b.png)
